// apps/octopus-pizza/src/components/Pizza.vue
<script setup lang="ts">
import { computed } from 'vue'
import { doOrder} from '../graph/doOrder'
import {pizza} from '../graph/Pizza'


const errorActive = computed(()=>{
    return pizza.val?.canChoose && !pizza.val?.valid && (doOrder.val?.submitBlocked || pizza.val?.touched)
})

const errorMsg = computed(()=>{
    if(pizza.val?.valid)
    return ""
    else if(!!pizza.val?.selectedValue)
    return "Your choice is not compatible with your base"
    else
    return "Please choose"
})

</script>

<template>
    <div class="option-container">
        <div v-for="(option, index) in pizza.val?.optionValues" :class="{
            'button': true,
            selected: option.selected,
            hide: option.hide
        }" @click="pizza.methods.selectItem(index)"><div>{{ option.valueName }} €{{ option.price?.toFixed(2) }}</div></div>
        <div class="container-title"><div>choose your pizza</div></div>
        <div :class="{'container-error':true, active: errorActive}"><div>{{ errorMsg }}</div></div>
    </div>
</template>

<style >
.option-container {
    color: var(--color-orange)
}
</style>

// apps/octopus-pizza-react/src/components/Pizza.tsx
import { doOrder } from "../graph/doOrder";
import { observer } from "mobx-react-lite";
import { IOption, IOptionMethods } from "../IOption";
import { INode } from "octopus-state-graph";
import { action } from "mobx";

export const Pizza = observer(
  ({ pizza }: { pizza: INode<IOption, IOptionMethods> }) => {
    const errorActive =
      pizza.val?.canChoose &&
      !pizza.val?.valid &&
      (doOrder.val?.submitBlocked || pizza.val?.touched);

    const errorMsg = pizza.val?.valid
      ? ""
      : pizza.val?.selectedValue
      ? "Your choice is not compatible with your base"
      : "Please choose";

    return (
      <>
        <div className="option-container">
          {pizza.val?.optionValues.map((option, index) => (
            <div
              className={`button ${option.selected ? "selected" : ""} ${
                option.hide ? "hide" : ""
              }`}
              onClick={action(() => pizza.methods?.selectItem(index))}
              key={option.valueName}
            >
              <div>
                {option.valueName} €{option.price?.toFixed(2)}
              </div>
            </div>
          ))}

          <div className="container-title">
            <div>choose your pizza</div>
          </div>
          <div className={`container-error ${errorActive ? "active" : ""}`}>
            <div>{errorMsg}</div>
          </div>
        </div>
      </>
    );
  }
);
