// apps/octopus-pizza/src/components/Tip.vue
<template>
    <div class="option-container" style="display:block; margin-top:50px;">
        <div class="container-title">tip</div>
        <input type="radio" id="tipAsPct" name="tipPercent" :value="true" v-model="tipAsPct"> 
        <label for="tipAsPct">10%</label>
        <span v-if="tipAsPct" style="font-size: smaller; padding-left: 10px;">({{tip.val?.optionPrice.toFixed(2)}} €)</span>
        <br>
        <br>
        <input type="radio" name="tipPercent" :value="false" v-model="tipAsPct">&nbsp;
        <input type="text" 
            v-model="amountInput" 
            @focus="tipAmountInputOnFocus()" @blur="tipAmountInputOnBlur()"
            @keypress="tipAmountInputOnKeypress($event)" id="tipAmountText"
            size="5"
        >&nbsp;€
    <div :class="{'container-error':true, active:(doOrder.val?.submitBlocked || tip.val?.touched) && !tip.val?.valid}"><div>Must not be empty</div></div>
    </div>
</template>

<script setup lang="ts">
import { computed, inject, ref } from 'vue';
import {tip} from "../graph/tip"
import {doOrder} from "../graph/doOrder"
// tipUI has an inner loop. User input is backed by a local variable in the vue component.
// Only if it parses to a number will we update the graph.
var _rawUI = ref("")
var amountActive = ref(false)
function tipAmountInputOnFocus() {
    if (tip.val?.parsedUserInput)
        _rawUI.value = tip.val?.parsedUserInput?.toFixed(2)
    amountActive.value = true
}
function tipAmountInputOnBlur() {
    amountActive.value = false
}
function tipAmountInputOnKeypress(e: KeyboardEvent) {
    if (e.target) {
        const tgt = e.target as HTMLInputElement
        const i = tgt.selectionStart || 0
        const currVal = tgt.value
        const futureVal = currVal.slice(0, i) + e.key + currVal.slice(i + Math.abs(0))
        if (/^[1-9]?[0-9]*\.?[0-9]{0,2}$/.test(futureVal))
            return true
        else {
            e.preventDefault()
            return false
        }
    }
}
const amountInput = computed({
    get() {
        if (amountActive.value) {
            return _rawUI.value
        } else {
            // if empty string, display it
            if (!_rawUI.value)
                return _rawUI.value
            else
                return tip.val?.parsedUserInput?.toFixed(2)
        }
    },
    set(newVal) {
        _rawUI.value = newVal || ''
        const parsedUI = parseFloat(newVal || '0')
        // keyup handler ensures only numbers are entered
        tip.methods.tipAmountOnChange(isNaN(parsedUI)? null: parsedUI)
    }
})

const tipAsPct = computed({
    get() { return tip.val?.tipAsPct },
    set(newVal) { tip.methods.setTipAsPct(newVal) }
})

</script>

<style scoped></style>

// apps/octopus-pizza-react/src/components/Tip.tsx

import {tip} from "../graph/tip"
import {doOrder} from "../graph/doOrder"
import { observer } from "mobx-react-lite"
import { useState } from "react"
import { action } from "mobx"
// tipUI has an inner loop. User input is backed by a local variable in the vue component.
// Only if it parses to a number will we update the graph.

export const Tip = observer(()=>{
    const [rawUi, setRawUi] = useState("")
    const [amountActive, setAmountActive] = useState(false)
    function tipAmountInputOnFocus() {
        if (tip.val?.parsedUserInput)
            setRawUi(tip.val?.parsedUserInput?.toFixed(2))
        setAmountActive(true)
    }
    function tipAmountInputOnBlur() {
        setAmountActive(false)
    }
    function tipAmountInputOnKeypress(e: React.KeyboardEvent<HTMLInputElement>) {
        if (e.target) {
            const tgt = e.target as HTMLInputElement
            const i = tgt.selectionStart || 0
            const currVal = tgt.value
            const futureVal = currVal.slice(0, i) + e.key + currVal.slice(i + Math.abs(0))
            if (/^[1-9]?[0-9]*\.?[0-9]{0,2}$/.test(futureVal))
                return true
            else {
                e.preventDefault()
                return false
            }
        }
    }
    // eslint-disable-next-line prefer-const
    let amountInput = {
        get value() {
            if (amountActive) {
                return rawUi
            } else {
                // if empty string, display it
                if (!rawUi)
                    return rawUi
                else
                    return tip.val?.parsedUserInput?.toFixed(2)
            }
        },
        set value(newVal:string|undefined) {
            setRawUi(newVal || '')
            const parsedUI = parseFloat(newVal||'')
            // keyup handler ensures only numbers are entered
            tip.methods.tipAmountOnChange(isNaN(parsedUI)? null: parsedUI)
        }
    }
    
    return (
    <>
        <div className="option-container" style={{display:"block", marginTop:"50px"}}>
            <div className="container-title">tip</div>
            <input type="radio" id="tipAsPct" name="tipPercent" checked={tip.val?.tipAsPct} onChange={action(()=>{ tip.methods.setTipAsPct(true) })}/> 
            <label htmlFor="tipAsPct">10%</label>
            {tip.val?.tipAsPct?(<span style={{fontSize:"smaller", paddingLeft:"10px"}}>({tip.val?.optionPrice.toFixed(2)} €)</span>):null}
            <br/>
            <br/>
            <input type="radio" name="tipPercent" checked={!tip.val?.tipAsPct} onChange={action(()=>{ tip.methods.setTipAsPct(false) })}/>&nbsp;
            <input type="text"
                onInput={action((event)=>{amountInput.value = ((event as React.FormEvent<HTMLInputElement>).currentTarget.value )})}
                value={amountInput.value}
                onFocus={action(()=>{tipAmountInputOnFocus()})}
                onBlur={action(()=>{tipAmountInputOnBlur()})}
                onKeyPress={action((event)=>{tipAmountInputOnKeypress(event)})}
                id="tipAmountText"
                size={5}
            />&nbsp;€
        <div className={`container-error ${(doOrder.val?.submitBlocked || tip.val?.touched) && !tip.val?.valid ? "active":""}`}
        ><div>Must not be empty</div></div>
        </div>
    </>
    )
})
