// apps/octopus-pizza-react/src/components/Base.tsx
import { observer } from "mobx-react-lite";
import { base } from "../graph/base";
import { action } from "mobx";
import { IOptionValue } from "../IOptionValue";
import { doOrder } from "../graph/doOrder";

export const Base = observer(() => {
  return (
    <>
      <div className="option-container base">
        {base.val?.optionValues.map((b: IOptionValue, index: number) => (
          <div
            className={`button ${b.selected ? "selected" : ""}`}
            onClick={action(() => base.methods?.selectItem(index))}
          >
            <div>{b.valueName}</div>
          </div>
        ))}
        <div className="container-title">
          <div>base</div>
        </div>
        <div 
          className={`container-error ${
            (doOrder.val?.submitBlocked || base.val?.touched) &&
            !base.val?.valid
              ? "active"
              : ""
          }`}>
          <div>Please choose</div>
        </div>
      </div>
    </>
  );
});

// apps/octopus-pizza/src/components/Base.vue
<script setup lang="ts">
import { inject, ref } from 'vue'
import {base} from "../graph/base"
import {doOrder} from "../graph/doOrder"

</script>

<template>
    <div class="option-container">
        <div v-for="(option, index) in base.val?.optionValues" :class="['button', option.selected ? 'selected' : '']"
            @click=" base.methods?.selectItem(index)">
            <div>{{ option.valueName }}</div>
        </div>
        <div class="container-title">
            <div>base</div>
        </div>
        <div :class="{'container-error':true, active:(doOrder.val?.submitBlocked || base.val?.touched) && !base.val?.valid}"><div>Please choose</div></div>
    </div>
</template>

<style scoped>
.option-container {
    color: var(--color-khaki)
}
</style>
