// apps/octopus-pizza-react/src/components/Size.tsx
import { action } from "mobx";
import { IOptionValue } from "../IOptionValue";
import { size } from "../graph/Size";
import { doOrder } from "../graph/doOrder";

export function Size() {
  return (
    <>
      <div className="option-container">
        {size.val?.optionValues.map((s: IOptionValue, index: number) => (
          <div
            className="['button',option.selected?'selected':'']"
            onClick={action('pickSize',()=>size.methods?.selectItem(index))}
            key={s.valueName}
          >
            <div>{s.valueName}</div>
          </div>
        ))}

        <div className="container-title">
          <div>size</div>
        </div>
        <div
          className={`container-error ${
            (doOrder.val?.submitBlocked || size.val?.touched) &&
            !size.val?.valid
              ? "active"
              : ""
          }`}
        >
          <div>Please choose</div>
        </div>
      </div>
    </>
  );

  // <style scoped>
  // .option-container{
  //     color: var(--color-purple)
  // }
  // </style>
}

// apps/octopus-pizza/src/components/Size.vue
<script setup lang="ts">
import { inject, ref } from 'vue'
import {size} from "../graph/Size"
import {doOrder} from "../graph/doOrder"

</script>

<template>
    <div class="option-container">
        <div v-for="(option, index) in size.val?.optionValues"
            :class="['button',option.selected?'selected':'']"
            @click="size.methods?.selectItem(index)"
        ><div>{{ option.valueName }}</div></div>
        <div class="container-title"><div>size</div></div>
        <div :class="{'container-error':true, active:(doOrder.val?.submitBlocked || size.val?.touched) && !size.val?.valid}"><div>Please choose</div></div>
    </div>
</template>

<style scoped>
.option-container{
    color: var(--color-purple)
}
</style>
